import { Effect } from "effect";
import type { ReviewContext, ReviewDomain, Understanding } from "@cyclops/domain";
import type { ClassifierPort, HarnessPort, ParserPort, ProofRenderPort, VcsPort } from "@cyclops/ports";
import { StoreError } from "@cyclops/ports";
import { understandingToProofSpec } from "@cyclops/application";

const pathDomainHints: Array<{ re: RegExp; domain: ReviewDomain }> = [
  { re: /auth|permission|secret/i, domain: "SECURITY" },
  { re: /pay|stripe|billing/i, domain: "PAYMENTS" },
  { re: /solana|wallet|crypto|chain/i, domain: "CRYPTO" },
  { re: /\.tsx$|components\//i, domain: "FRONTEND" },
  { re: /docker|k8s|terraform/i, domain: "INFRASTRUCTURE" },
  { re: /\.yml$|workflow|ci/i, domain: "DEVOPS" },
  { re: /sql|migration|schema/i, domain: "DATABASE" },
];

export const makeHeuristicClassifier = (): ClassifierPort => ({
  classify: ({ title, body, paths }) =>
    Effect.sync(() => {
      const blob = `${title}\n${body}\n${paths.join("\n")}`;
      for (const h of pathDomainHints) {
        if (h.re.test(blob)) {
          return { domain: h.domain, focus: undefined, confidence: 0.6 };
        }
      }
      return { domain: "GENERAL" as const, confidence: 0.3 };
    }),
});

export const makeStubHarness = (): HarnessPort => ({
  runUnderstand: ({ diff, context, role }) =>
    Effect.sync(() => {
      const understanding: Understanding = {
        what: `Review (${role}) of change affecting ${context.domain}${context.focus ? `×${context.focus}` : ""}`,
        why: "Generated by stub harness for dogfood until Pi adapter is wired to a live model.",
        how: `Inspected diff (${diff.length} chars). Context wiki hits: ${context.wiki_hits.length}, pr graph: ${context.pr_graph.length}.`,
        proof_refs: [{ kind: "command", label: "diff-stats", value: `chars=${diff.length}` }],
        out_of_scope: [],
        risks: [
          {
            area: "stub",
            note: "Replace stub harness with Pi for production-quality understanding.",
            source: "reviewer",
          },
        ],
      };
      return understanding;
    }),
});

export const makeProofRender = (): ProofRenderPort => ({
  toSpec: ({ understanding, context, risksReviewer }) =>
    understandingToProofSpec({
      understanding: {
        ...understanding,
        risks: [...understanding.risks, ...risksReviewer],
      },
      domain: context.domain,
      focus: context.focus,
      reviewerRisks: risksReviewer,
    }),
});

/** Regex/tree-lite symbol extract — upgraded by treesitter adapter when available. */
export const makeRegexParser = (): ParserPort => ({
  extractSymbols: (path, source) =>
    Effect.sync(() => {
      const out: Array<{ name: string; kind: string; startLine: number; endLine: number }> = [];
      const lines = source.split(/\r?\n/);
      const re =
        path.endsWith(".go")
          ? /^func\s+(\w+)/
          : /^(?:export\s+)?(?:async\s+)?function\s+(\w+)|^(?:export\s+)?(?:const|class|type|interface)\s+(\w+)/;
      lines.forEach((line, i) => {
        const m = re.exec(line);
        const name = m?.[1] ?? m?.[2];
        if (name) out.push({ name, kind: "symbol", startLine: i + 1, endLine: i + 1 });
      });
      return out;
    }),
});

export const makeFakeVcs = (): VcsPort => ({
  fetchPullRequest: (owner, repo, number) =>
    Effect.succeed({
      pr: {
        id: `pr:${owner}/${repo}#${number}`,
        repoId: `repo:${owner}/${repo}`,
        number,
        title: `Fake PR ${number}`,
        body: "dogfood",
        author: "dogfood-bot",
        baseRef: "main",
        headRef: "feature",
        url: `https://github.com/${owner}/${repo}/pull/${number}`,
      },
      closingNumbers: [],
      changedPaths: ["README.md"],
    }),
});
