import type {
  ArchEdge,
  ArchNode,
  CICheck,
  Comment,
  CompatRow,
  FileChange,
  Insight,
  ReviewStep,
  RiskCluster,
  TimelineEvent,
} from "./types";

export const PR = {
  repo: "osp-protocol/osp",
  number: 482,
  title: "protocol: signed request envelopes (v0.9) + capability scopes",
  author: "mkorkmaz",
  branch: "feat/signed-envelopes",
  base: "main",
  createdAt: "2026-07-13T09:12:00Z",
  additions: 2841,
  deletions: 612,
  commits: 14,
  reviewProgress: 0.35,
  description:
    "Introduces the v0.9 signed request envelope: every SDK call is wrapped in a canonical, Ed25519-signed envelope with a nonce and expiry. Adds capability scopes so a key can be restricted to a subset of methods. Ships parallel implementations in the TS core, Rust and Python SDKs plus conformance vectors.",
};

export const files: FileChange[] = [
  // ---- Protocol spec ----
  {
    path: "spec/envelope.md",
    lang: "md",
    additions: 214,
    deletions: 8,
    risk: 2,
    group: "Protocol spec",
    comments: 3,
    tests: [],
    protocol: true,
    summary:
      "Defines the v0.9 envelope: canonical JSON serialization, Ed25519 signature over (method, params, nonce, exp), 90s expiry window.",
  },
  {
    path: "spec/capabilities.md",
    lang: "md",
    additions: 122,
    deletions: 0,
    risk: 1,
    group: "Protocol spec",
    comments: 1,
    tests: [],
    protocol: true,
    summary:
      "New capability-scope grammar: `method:namespace/*` patterns, deny-by-default resolution order.",
  },
  {
    path: "spec/CHANGELOG.md",
    lang: "md",
    additions: 18,
    deletions: 0,
    risk: 0,
    group: "Protocol spec",
    comments: 0,
    tests: [],
    protocol: true,
    summary: "v0.9 changelog entry; marks v0.8 unsigned requests deprecated.",
  },
  // ---- TS core ----
  {
    path: "packages/core/src/envelope.ts",
    lang: "ts",
    additions: 186,
    deletions: 24,
    risk: 3,
    group: "TS core",
    comments: 4,
    tests: ["envelope.test.ts", "conformance/runner.ts"],
    protocol: true,
    security: true,
    summary:
      "Envelope builder: canonicalizes payload (RFC 8785), attaches nonce + exp, signs with Ed25519. The canonicalization here is what every other SDK must byte-match.",
    hunk: {
      header: "@@ -41,9 +41,32 @@ export function buildEnvelope(req: Request, key: SigningKey)",
      lines: [
        { kind: "ctx", no: 41, text: "export function buildEnvelope(req: Request, key: SigningKey): Envelope {" },
        { kind: "del", no: 42, text: "  const payload = JSON.stringify(req);" },
        { kind: "add", no: 42, text: "  const payload = canonicalize({" },
        { kind: "add", no: 43, text: "    method: req.method," },
        { kind: "add", no: 44, text: "    params: req.params," },
        { kind: "add", no: 45, text: "    nonce: randomNonce()," },
        { kind: "add", no: 46, text: "    exp: now() + EXPIRY_SECONDS," },
        { kind: "add", no: 47, text: "  });" },
        { kind: "add", no: 48, text: "  const sig = ed25519.sign(key.secret, utf8(payload));" },
        { kind: "ctx", no: 49, text: "  return { v: 9, payload, sig: base64url(sig) };" },
        { kind: "ctx", no: 50, text: "}" },
      ],
    },
  },
  {
    path: "packages/core/src/verify.ts",
    lang: "ts",
    additions: 158,
    deletions: 12,
    risk: 3,
    group: "TS core",
    comments: 5,
    tests: ["verify.test.ts"],
    protocol: true,
    security: true,
    summary:
      "Server-side verification: signature check, nonce replay cache, expiry window. Contains the clock-skew tolerance logic under discussion.",
    hunk: {
      header: "@@ -63,4 +63,14 @@ export function verifyEnvelope(env: Envelope, opts: VerifyOpts)",
      lines: [
        { kind: "ctx", no: 63, text: "  if (!ed25519.verify(key.public, utf8(env.payload), sig)) {" },
        { kind: "ctx", no: 64, text: "    return reject(\"bad_signature\");" },
        { kind: "ctx", no: 65, text: "  }" },
        { kind: "add", no: 66, text: "  const skew = opts.maxClockSkew ?? 30; // seconds" },
        { kind: "add", no: 67, text: "  if (body.exp + skew < now()) return reject(\"expired\");" },
        { kind: "add", no: 68, text: "  if (nonceCache.has(body.nonce)) return reject(\"replay\");" },
        { kind: "add", no: 69, text: "  nonceCache.put(body.nonce, body.exp + skew);" },
        { kind: "ctx", no: 70, text: "  return accept(body);" },
      ],
    },
  },
  {
    path: "packages/core/src/scopes.ts",
    lang: "ts",
    additions: 142,
    deletions: 0,
    risk: 3,
    group: "TS core",
    comments: 2,
    tests: ["scopes.test.ts"],
    protocol: true,
    security: true,
    summary:
      "Capability-scope matcher. Glob-style `payments/*` patterns compiled to a prefix trie; deny-by-default.",
    hunk: {
      header: "@@ -0,0 +18,12 @@ export function scopeAllows(scopes: string[], method: string)",
      lines: [
        { kind: "add", no: 18, text: "export function scopeAllows(scopes: string[], method: string): boolean {" },
        { kind: "add", no: 19, text: "  for (const s of scopes) {" },
        { kind: "add", no: 20, text: "    if (s.endsWith(\"/*\")) {" },
        { kind: "add", no: 21, text: "      if (method.startsWith(s.slice(0, -1))) return true;" },
        { kind: "add", no: 22, text: "    } else if (s === method) return true;" },
        { kind: "add", no: 23, text: "  }" },
        { kind: "add", no: 24, text: "  return false; // deny by default" },
        { kind: "add", no: 25, text: "}" },
      ],
    },
  },
  {
    path: "packages/core/src/nonce.ts",
    lang: "ts",
    additions: 74,
    deletions: 0,
    risk: 2,
    group: "TS core",
    comments: 1,
    tests: ["nonce.test.ts"],
    security: true,
    summary:
      "In-memory nonce replay cache with TTL eviction. Single-process only; distributed deployments need an external store.",
  },
  {
    path: "packages/core/src/canonical.ts",
    lang: "ts",
    additions: 96,
    deletions: 0,
    risk: 3,
    group: "TS core",
    comments: 2,
    tests: ["canonical.test.ts", "conformance/runner.ts"],
    protocol: true,
    summary:
      "RFC 8785 JSON canonicalization. Key sort order and number formatting must byte-match Rust and Python implementations.",
  },
  {
    path: "packages/core/src/errors.ts",
    lang: "ts",
    additions: 31,
    deletions: 4,
    risk: 0,
    group: "TS core",
    comments: 0,
    tests: [],
    summary: "New error codes: bad_signature, expired, replay, scope_denied.",
  },
  {
    path: "packages/core/src/index.ts",
    lang: "ts",
    additions: 12,
    deletions: 2,
    risk: 0,
    group: "TS core",
    comments: 0,
    tests: [],
    summary: "Re-exports envelope, verify, scopes.",
  },
  {
    path: "packages/core/test/verify.test.ts",
    lang: "ts",
    additions: 168,
    deletions: 6,
    risk: 0,
    group: "TS core",
    comments: 0,
    tests: [],
    summary: "Verification tests incl. replay, expiry, skew boundaries.",
  },
  // ---- Node SDK ----
  {
    path: "packages/sdk-node/src/client.ts",
    lang: "ts",
    additions: 88,
    deletions: 41,
    risk: 2,
    group: "Node SDK",
    comments: 2,
    tests: ["client.test.ts"],
    summary:
      "Client now wraps every call in buildEnvelope(). Retry path re-signs with a fresh nonce instead of resending the original envelope.",
  },
  {
    path: "packages/sdk-node/src/retry.ts",
    lang: "ts",
    additions: 54,
    deletions: 18,
    risk: 2,
    group: "Node SDK",
    comments: 3,
    tests: ["retry.test.ts"],
    security: true,
    summary:
      "Retries mint a new envelope per attempt. Idempotency key is carried in params so the server can dedupe across differently-signed retries.",
  },
  {
    path: "packages/sdk-node/src/middleware.ts",
    lang: "ts",
    additions: 61,
    deletions: 9,
    risk: 1,
    group: "Node SDK",
    comments: 0,
    tests: ["middleware.test.ts"],
    summary: "Express/Hono middleware verifying inbound envelopes.",
  },
  {
    path: "packages/sdk-node/test/client.test.ts",
    lang: "ts",
    additions: 92,
    deletions: 10,
    risk: 0,
    group: "Node SDK",
    comments: 0,
    tests: [],
    summary: "Client signing tests.",
  },
  // ---- Rust SDK ----
  {
    path: "sdks/rust/src/envelope.rs",
    lang: "rs",
    additions: 171,
    deletions: 30,
    risk: 3,
    group: "Rust SDK",
    comments: 3,
    tests: ["envelope_test.rs", "conformance"],
    protocol: true,
    security: true,
    summary:
      "Rust envelope builder. Uses serde_jcs for canonicalization — float formatting differs from the TS implementation for exponents ≥ 1e21.",
    hunk: {
      header: "@@ -55,6 +55,13 @@ pub fn build_envelope(req: &Request, key: &SigningKey)",
      lines: [
        { kind: "ctx", no: 55, text: "pub fn build_envelope(req: &Request, key: &SigningKey) -> Envelope {" },
        { kind: "add", no: 56, text: "    let body = EnvelopeBody {" },
        { kind: "add", no: 57, text: "        method: req.method.clone()," },
        { kind: "add", no: 58, text: "        params: req.params.clone()," },
        { kind: "add", no: 59, text: "        nonce: random_nonce()," },
        { kind: "add", no: 60, text: "        exp: unix_now() + EXPIRY_SECONDS," },
        { kind: "add", no: 61, text: "    };" },
        { kind: "add", no: 62, text: "    let payload = serde_jcs::to_string(&body).expect(\"canonical\");" },
        { kind: "ctx", no: 63, text: "    let sig = key.sign(payload.as_bytes());" },
      ],
    },
  },
  {
    path: "sdks/rust/src/verify.rs",
    lang: "rs",
    additions: 129,
    deletions: 11,
    risk: 2,
    group: "Rust SDK",
    comments: 1,
    tests: ["verify_test.rs"],
    protocol: true,
    security: true,
    summary: "Rust-side verification, mirrors TS logic. Skew default matches (30s).",
  },
  {
    path: "sdks/rust/src/scopes.rs",
    lang: "rs",
    additions: 98,
    deletions: 0,
    risk: 2,
    group: "Rust SDK",
    comments: 1,
    tests: ["scopes_test.rs"],
    security: true,
    summary:
      "Scope matcher. Uses simple prefix match — does not compile a trie; O(scopes) per call, fine at current sizes.",
  },
  {
    path: "sdks/rust/src/lib.rs",
    lang: "rs",
    additions: 14,
    deletions: 3,
    risk: 0,
    group: "Rust SDK",
    comments: 0,
    tests: [],
    summary: "Module exports.",
  },
  {
    path: "sdks/rust/tests/envelope_test.rs",
    lang: "rs",
    additions: 104,
    deletions: 0,
    risk: 0,
    group: "Rust SDK",
    comments: 0,
    tests: [],
    summary: "Envelope round-trip tests against conformance vectors.",
  },
  {
    path: "sdks/rust/Cargo.toml",
    lang: "yml",
    additions: 6,
    deletions: 1,
    risk: 1,
    group: "Rust SDK",
    comments: 1,
    tests: [],
    summary: "Adds ed25519-dalek 2.x and serde_jcs. dalek 2.x bumps MSRV to 1.72.",
  },
  // ---- Python SDK ----
  {
    path: "sdks/python/osp/envelope.py",
    lang: "py",
    additions: 148,
    deletions: 22,
    risk: 3,
    group: "Python SDK",
    comments: 2,
    tests: ["test_envelope.py", "conformance"],
    protocol: true,
    security: true,
    summary:
      "Python envelope builder. Hand-rolled canonicalization (sort_keys + separators) instead of a JCS library — the current failure in CI.",
    hunk: {
      header: "@@ -33,5 +33,11 @@ def build_envelope(req, key):",
      lines: [
        { kind: "ctx", no: 33, text: "def build_envelope(req: Request, key: SigningKey) -> Envelope:" },
        { kind: "add", no: 34, text: "    body = {\"method\": req.method, \"params\": req.params," },
        { kind: "add", no: 35, text: "            \"nonce\": random_nonce(), \"exp\": _now() + EXPIRY_SECONDS}" },
        { kind: "add", no: 36, text: "    payload = json.dumps(body, sort_keys=True, separators=(\",\", \":\"))" },
        { kind: "add", no: 37, text: "    sig = key.sign(payload.encode())" },
        { kind: "ctx", no: 38, text: "    return Envelope(v=9, payload=payload, sig=b64url(sig))" },
      ],
    },
  },
  {
    path: "sdks/python/osp/verify.py",
    lang: "py",
    additions: 117,
    deletions: 9,
    risk: 2,
    group: "Python SDK",
    comments: 2,
    tests: ["test_verify.py"],
    protocol: true,
    security: true,
    summary:
      "Python verification. Uses time.time() directly; monotonic-clock question raised in review.",
  },
  {
    path: "sdks/python/osp/scopes.py",
    lang: "py",
    additions: 71,
    deletions: 0,
    risk: 2,
    group: "Python SDK",
    comments: 1,
    tests: ["test_scopes.py"],
    security: true,
    summary:
      "Scope matcher. Uses fnmatch — accepts `?` and `[seq]` wildcards the spec does not define. Wider than TS/Rust.",
  },
  {
    path: "sdks/python/osp/__init__.py",
    lang: "py",
    additions: 9,
    deletions: 1,
    risk: 0,
    group: "Python SDK",
    comments: 0,
    tests: [],
    summary: "Exports.",
  },
  {
    path: "sdks/python/tests/test_envelope.py",
    lang: "py",
    additions: 121,
    deletions: 4,
    risk: 0,
    group: "Python SDK",
    comments: 0,
    tests: [],
    summary: "Envelope tests; two conformance cases currently failing.",
  },
  {
    path: "sdks/python/pyproject.toml",
    lang: "yml",
    additions: 4,
    deletions: 1,
    risk: 0,
    group: "Python SDK",
    comments: 0,
    tests: [],
    summary: "Adds pynacl dependency.",
  },
  // ---- Conformance ----
  {
    path: "conformance/vectors/envelope-v9.json",
    lang: "json",
    additions: 342,
    deletions: 0,
    risk: 2,
    group: "Conformance",
    comments: 1,
    tests: [],
    protocol: true,
    summary:
      "48 canonical envelope vectors: unicode keys, large integers, float edge cases, empty params.",
  },
  {
    path: "conformance/runner.ts",
    lang: "ts",
    additions: 128,
    deletions: 17,
    risk: 1,
    group: "Conformance",
    comments: 0,
    tests: [],
    summary: "Cross-SDK conformance runner; shells out to each SDK and compares canonical bytes.",
  },
  {
    path: "conformance/vectors/scopes.json",
    lang: "json",
    additions: 96,
    deletions: 0,
    risk: 1,
    group: "Conformance",
    comments: 0,
    tests: [],
    protocol: true,
    summary: "Scope-matching vectors incl. adversarial patterns (`payments/*x`, trailing slash).",
  },
  {
    path: "conformance/README.md",
    lang: "md",
    additions: 44,
    deletions: 2,
    risk: 0,
    group: "Conformance",
    comments: 0,
    tests: [],
    summary: "How to run the conformance suite locally.",
  },
  // ---- Infra / docs ----
  {
    path: ".github/workflows/ci.yml",
    lang: "yml",
    additions: 38,
    deletions: 6,
    risk: 1,
    group: "Infra & docs",
    comments: 0,
    tests: [],
    summary: "Adds conformance job; python matrix now 3.10–3.13.",
  },
  {
    path: "docs/migration-v9.md",
    lang: "md",
    additions: 88,
    deletions: 0,
    risk: 1,
    group: "Infra & docs",
    comments: 1,
    tests: [],
    summary:
      "Migration guide v0.8 → v0.9. Dual-stack window: servers accept unsigned requests until 2026-10-01.",
  },
  {
    path: "docs/api/envelope.md",
    lang: "md",
    additions: 52,
    deletions: 11,
    risk: 0,
    group: "Infra & docs",
    comments: 0,
    tests: [],
    summary: "API docs for the new envelope helpers.",
  },
  {
    path: "README.md",
    lang: "md",
    additions: 12,
    deletions: 6,
    risk: 0,
    group: "Infra & docs",
    comments: 0,
    tests: [],
    summary: "Quickstart updated to signed calls.",
  },
];

export const checks: CICheck[] = [
  { id: "build", name: "build / turbo", status: "pass", duration: "2m 41s" },
  { id: "types", name: "typecheck / tsc --strict", status: "pass", duration: "1m 12s" },
  { id: "test-ts", name: "test / ts-core + node-sdk", status: "pass", duration: "3m 05s" },
  { id: "test-rust", name: "test / rust-sdk", status: "pass", duration: "4m 22s" },
  {
    id: "test-py",
    name: "test / python-sdk (3.10–3.13)",
    status: "fail",
    duration: "1m 58s",
    detail: "2 failures in test_envelope.py — canonical bytes mismatch on float vectors",
    logTail: [
      "FAILED tests/test_envelope.py::test_vector_31_float_exponent",
      "FAILED tests/test_envelope.py::test_vector_34_negative_zero",
      "AssertionError: b'…\"amount\":1e+21…' != b'…\"amount\":1e21…'",
      "──── json.dumps float repr diverges from RFC 8785 for |x| ≥ 1e21 and -0.0",
    ],
  },
  {
    id: "conformance",
    name: "conformance / cross-sdk vectors",
    status: "fail",
    duration: "5m 44s",
    detail: "python disagrees with ts/rust on 2 of 48 envelope vectors",
    logTail: [
      "vector 31: ts ✓ rust ✓ python ✗ (float exponent form)",
      "vector 34: ts ✓ rust ✓ python ✗ (-0.0 serialized as -0)",
      "46/48 vectors byte-identical across all three SDKs",
    ],
  },
  { id: "audit", name: "security / cargo-audit + npm-audit", status: "pass", duration: "58s" },
];

export const insights: Insight[] = [
  {
    id: "ins-canon",
    kind: "compat",
    title: "Python canonicalization diverges from RFC 8785 on float edge cases",
    body: "TS uses a JCS library and Rust uses serde_jcs, but Python hand-rolls canonicalization with json.dumps(sort_keys=True). Python's float repr disagrees with JCS for |x| ≥ 1e21 and -0.0, which is exactly what conformance vectors 31 and 34 catch. Any envelope containing such a number will fail signature verification cross-SDK.",
    confidence: 0.96,
    reasoning:
      "Both failing CI jobs point at the same two vectors; the diff shows json.dumps in envelope.py while the other SDKs use JCS implementations. This is a byte-compatibility break, not a test flake.",
    evidence: [
      {
        id: "ev-canon-1",
        file: "sdks/python/osp/envelope.py",
        lines: "36",
        excerpt: "payload = json.dumps(body, sort_keys=True, separators=(\",\", \":\"))",
        note: "Hand-rolled canonicalization — not RFC 8785 compliant for float edge cases.",
      },
      {
        id: "ev-canon-2",
        file: "conformance/vectors/envelope-v9.json",
        lines: "vector 31, 34",
        excerpt: "\"amount\": 1e21  /  \"delta\": -0.0",
        note: "The two vectors python fails; ts and rust agree with each other.",
      },
      {
        id: "ev-canon-3",
        file: "packages/core/src/canonical.ts",
        lines: "1–96",
        excerpt: "RFC 8785 JSON canonicalization implementation",
        note: "The reference implementation the other SDKs must byte-match.",
      },
    ],
    files: ["sdks/python/osp/envelope.py", "conformance/vectors/envelope-v9.json"],
  },
  {
    id: "ins-scope-fnmatch",
    kind: "security",
    title: "Python scope matcher is wider than the spec",
    body: "scopes.py uses fnmatch, which honors `?` and `[seq]` wildcards. The spec only defines `namespace/*` suffix globs. A scope string like `payments/[a-z]*` would be inert in TS/Rust but permissive in Python — a cross-SDK authorization inconsistency.",
    confidence: 0.88,
    reasoning:
      "spec/capabilities.md defines only the trailing-star form. fnmatch semantics are strictly wider. No conformance vector currently covers `?` or `[seq]` patterns, so CI cannot catch it.",
    evidence: [
      {
        id: "ev-fn-1",
        file: "sdks/python/osp/scopes.py",
        lines: "22",
        excerpt: "return any(fnmatch.fnmatch(method, s) for s in scopes)",
        note: "fnmatch accepts ?, [seq] — wider than the spec grammar.",
      },
      {
        id: "ev-fn-2",
        file: "spec/capabilities.md",
        lines: "§2.1",
        excerpt: "A scope is either an exact method name or `namespace/*`.",
        note: "Spec grammar defines only two forms.",
      },
    ],
    files: ["sdks/python/osp/scopes.py", "spec/capabilities.md"],
  },
  {
    id: "ins-nonce",
    kind: "security",
    title: "Replay protection is single-process only",
    body: "The nonce cache is an in-memory map with TTL eviction. Behind a load balancer, a captured envelope can be replayed against a different instance within its 90s + 30s skew window. Fine for the default single-node deployment; needs a shared store (or an explicit doc warning) for horizontal deployments.",
    confidence: 0.83,
    reasoning:
      "nonce.ts has no storage interface; verify.ts consumes it directly. The migration doc does not mention multi-instance deployments.",
    evidence: [
      {
        id: "ev-nonce-1",
        file: "packages/core/src/nonce.ts",
        lines: "9–41",
        excerpt: "const cache = new Map<string, number>(); // nonce → expiry",
        note: "Process-local map; no pluggable backend.",
      },
      {
        id: "ev-nonce-2",
        file: "docs/migration-v9.md",
        lines: "—",
        excerpt: "(no section on multi-instance deployments)",
        note: "Gap: operators are not warned.",
      },
    ],
    files: ["packages/core/src/nonce.ts", "docs/migration-v9.md"],
  },
  {
    id: "ins-retry",
    kind: "correctness",
    title: "Retry re-signing interacts correctly with replay protection",
    body: "Retries mint a fresh nonce per attempt (rather than resending the original envelope), so the replay cache never rejects a legitimate retry. Idempotency is preserved by carrying the idempotency key inside signed params. This is the right design; the subtle part is that a retry after server-side success is only deduped if the handler honors the key.",
    confidence: 0.79,
    reasoning:
      "retry.ts re-invokes buildEnvelope per attempt; client.test.ts asserts distinct nonces across attempts and stable idempotency keys.",
    evidence: [
      {
        id: "ev-retry-1",
        file: "packages/sdk-node/src/retry.ts",
        lines: "27–39",
        excerpt: "const env = buildEnvelope(withIdemKey(req), key); // fresh nonce per attempt",
        note: "New envelope per retry attempt.",
      },
    ],
    files: ["packages/sdk-node/src/retry.ts", "packages/sdk-node/src/client.ts"],
  },
  {
    id: "ins-skew",
    kind: "design",
    title: "30s clock-skew default is undocumented in the spec",
    body: "verify implementations accept envelopes up to exp + 30s. The tolerance is consistent across all three SDKs but lives only in code; the spec defines the 90s expiry without mentioning skew. Two independent implementations could legitimately disagree on validity of the same envelope.",
    confidence: 0.74,
    reasoning:
      "spec/envelope.md §4 defines exp semantics with no skew clause; all three verify implementations hardcode the same default.",
    evidence: [
      {
        id: "ev-skew-1",
        file: "packages/core/src/verify.ts",
        lines: "66",
        excerpt: "const skew = opts.maxClockSkew ?? 30; // seconds",
        note: "Default lives in code, not spec.",
      },
      {
        id: "ev-skew-2",
        file: "spec/envelope.md",
        lines: "§4",
        excerpt: "An envelope MUST be rejected after `exp`.",
        note: "No skew tolerance defined.",
      },
    ],
    files: ["packages/core/src/verify.ts", "spec/envelope.md"],
  },
  {
    id: "ins-msrv",
    kind: "compat",
    title: "ed25519-dalek 2.x raises Rust MSRV to 1.72",
    body: "Cargo.toml bumps ed25519-dalek to 2.x, which requires Rust 1.72+. The repo README advertises MSRV 1.70. Downstream embedded users pinning older toolchains will break on upgrade.",
    confidence: 0.68,
    reasoning:
      "dalek 2.x changelog states MSRV 1.72; repo docs claim 1.70. CI only tests stable, so the gap is invisible to checks.",
    evidence: [
      {
        id: "ev-msrv-1",
        file: "sdks/rust/Cargo.toml",
        lines: "14",
        excerpt: "ed25519-dalek = \"2\"",
        note: "MSRV 1.72 per upstream changelog.",
      },
    ],
    files: ["sdks/rust/Cargo.toml"],
  },
];

export const riskClusters: RiskCluster[] = [
  {
    id: "risk-canon",
    title: "Cross-SDK byte compatibility",
    level: 3,
    summary:
      "Three canonicalization implementations must produce identical bytes. Python currently doesn't — 2 of 48 vectors fail. This is the release blocker.",
    files: [
      "packages/core/src/canonical.ts",
      "sdks/rust/src/envelope.rs",
      "sdks/python/osp/envelope.py",
      "conformance/vectors/envelope-v9.json",
    ],
    insightId: "ins-canon",
  },
  {
    id: "risk-authz",
    title: "Authorization semantics drift",
    level: 3,
    summary:
      "Scope matching implemented three times with three mechanisms (trie, prefix, fnmatch). Python is wider than spec. Authorization must not depend on which SDK verifies.",
    files: [
      "packages/core/src/scopes.ts",
      "sdks/rust/src/scopes.rs",
      "sdks/python/osp/scopes.py",
      "spec/capabilities.md",
    ],
    insightId: "ins-scope-fnmatch",
  },
  {
    id: "risk-replay",
    title: "Replay window in distributed deployments",
    level: 2,
    summary:
      "In-memory nonce cache means replay protection is per-process. Horizontal deployments have a real replay window until a shared store exists.",
    files: ["packages/core/src/nonce.ts", "packages/core/src/verify.ts"],
    insightId: "ins-nonce",
  },
  {
    id: "risk-migration",
    title: "v0.8 → v0.9 migration window",
    level: 1,
    summary:
      "Dual-stack period accepts unsigned requests until 2026-10-01. Low risk, but the deprecation path must be loud in docs and telemetry.",
    files: ["docs/migration-v9.md", "spec/CHANGELOG.md"],
  },
];

export const reviewSteps: ReviewStep[] = [
  {
    id: "step-spec",
    title: "Read the spec deltas first",
    why: "Everything else implements these two documents. Verify the envelope layout and scope grammar are what you expect before reading code.",
    files: ["spec/envelope.md", "spec/capabilities.md"],
    minutes: 15,
    risk: 2,
  },
  {
    id: "step-canon",
    title: "Canonicalization, all three implementations side by side",
    why: "The highest-risk surface: byte-identical output is a hard requirement. Python is the outlier (hand-rolled, currently failing CI).",
    files: [
      "packages/core/src/canonical.ts",
      "sdks/rust/src/envelope.rs",
      "sdks/python/osp/envelope.py",
    ],
    minutes: 25,
    risk: 3,
  },
  {
    id: "step-verify",
    title: "Verification path: signature, expiry, replay",
    why: "Security-critical. Check skew handling and the nonce cache lifecycle against the spec.",
    files: ["packages/core/src/verify.ts", "packages/core/src/nonce.ts", "sdks/rust/src/verify.rs", "sdks/python/osp/verify.py"],
    minutes: 20,
    risk: 3,
  },
  {
    id: "step-scopes",
    title: "Scope matchers vs the grammar",
    why: "Deny-by-default must hold in all three SDKs. Pay attention to the fnmatch divergence in Python.",
    files: ["packages/core/src/scopes.ts", "sdks/rust/src/scopes.rs", "sdks/python/osp/scopes.py"],
    minutes: 15,
    risk: 3,
  },
  {
    id: "step-client",
    title: "Client integration and retry semantics",
    why: "Fresh nonce per retry + idempotency key inside signed params. Verify the dedupe story end to end.",
    files: ["packages/sdk-node/src/client.ts", "packages/sdk-node/src/retry.ts"],
    minutes: 12,
    risk: 2,
  },
  {
    id: "step-rest",
    title: "Conformance suite, CI, docs",
    why: "Mechanical review: vector coverage (add `?`/`[seq]` scope vectors), migration doc accuracy, workflow changes.",
    files: ["conformance/runner.ts", ".github/workflows/ci.yml", "docs/migration-v9.md"],
    minutes: 10,
    risk: 1,
  },
];

export const comments: Comment[] = [
  {
    id: "c1",
    author: "aylin-t",
    role: "maintainer",
    time: "2h ago",
    file: "packages/core/src/verify.ts",
    line: 66,
    body: "30s skew feels arbitrary — should this be in the spec? Two conforming implementations could disagree on the same envelope.",
    resolved: false,
    replies: 3,
    topic: "clock skew",
  },
  {
    id: "c2",
    author: "mkorkmaz",
    role: "author",
    time: "1h ago",
    file: "packages/core/src/verify.ts",
    line: 66,
    body: "Agreed. I'll add a `max_clock_skew` recommendation to §4 and make it configurable everywhere. Default stays 30s.",
    resolved: false,
    replies: 0,
    topic: "clock skew",
  },
  {
    id: "c3",
    author: "jrmorgan",
    role: "reviewer",
    time: "5h ago",
    file: "sdks/python/osp/envelope.py",
    line: 36,
    body: "json.dumps is not JCS. This is exactly why vectors 31/34 fail. Suggest using the `jcs` package or porting the TS canonicalizer.",
    resolved: false,
    replies: 2,
    topic: "canonicalization",
  },
  {
    id: "c4",
    author: "aylin-t",
    role: "maintainer",
    time: "4h ago",
    file: "sdks/python/osp/scopes.py",
    line: 22,
    body: "fnmatch accepts `?` and `[seq]` — wider than the grammar in capabilities.md §2.1. Needs an anchored regex or plain prefix logic.",
    resolved: false,
    replies: 1,
    topic: "scope matching",
  },
  {
    id: "c5",
    author: "chen-w",
    role: "reviewer",
    time: "8h ago",
    file: "packages/core/src/nonce.ts",
    line: 9,
    body: "Worth a doc note that this is per-process. People will put this behind an ALB and assume replay protection is global.",
    resolved: true,
    replies: 2,
    topic: "replay protection",
  },
  {
    id: "c6",
    author: "mkorkmaz",
    role: "author",
    time: "3h ago",
    file: "sdks/rust/Cargo.toml",
    line: 14,
    body: "Heads up: dalek 2.x bumps MSRV to 1.72. README still says 1.70 — will update in this PR.",
    resolved: false,
    replies: 0,
    topic: "MSRV",
  },
];

export const archNodes: ArchNode[] = [
  { id: "spec", label: "Protocol spec", kind: "spec", changed: true, detail: "envelope.md + capabilities.md define the wire format all SDKs implement.", files: ["spec/envelope.md", "spec/capabilities.md"], x: 50, y: 8 },
  { id: "canonical", label: "Canonicalization", kind: "core", changed: true, detail: "RFC 8785 serialization — the byte-compatibility contract.", files: ["packages/core/src/canonical.ts"], x: 22, y: 36 },
  { id: "envelope", label: "Envelope build/sign", kind: "core", changed: true, detail: "Wraps requests: canonical payload + nonce + exp, Ed25519 signature.", files: ["packages/core/src/envelope.ts"], x: 50, y: 36 },
  { id: "verify", label: "Verify + replay", kind: "core", changed: true, detail: "Signature check, expiry with skew, nonce replay cache.", files: ["packages/core/src/verify.ts", "packages/core/src/nonce.ts"], x: 78, y: 36 },
  { id: "scopes", label: "Capability scopes", kind: "core", changed: true, detail: "Deny-by-default method authorization.", files: ["packages/core/src/scopes.ts"], x: 8, y: 64 },
  { id: "sdk-node", label: "Node SDK", kind: "sdk", changed: true, detail: "Client wrapping, retries with fresh nonces, verify middleware.", files: ["packages/sdk-node/src/client.ts", "packages/sdk-node/src/retry.ts"], x: 33, y: 68 },
  { id: "sdk-rust", label: "Rust SDK", kind: "sdk", changed: true, detail: "Parallel implementation via serde_jcs + dalek.", files: ["sdks/rust/src/envelope.rs", "sdks/rust/src/verify.rs", "sdks/rust/src/scopes.rs"], x: 58, y: 68 },
  { id: "sdk-py", label: "Python SDK", kind: "sdk", changed: true, detail: "Parallel implementation; canonicalization currently non-conformant.", files: ["sdks/python/osp/envelope.py", "sdks/python/osp/verify.py", "sdks/python/osp/scopes.py"], x: 83, y: 68 },
  { id: "conformance", label: "Conformance suite", kind: "infra", changed: true, detail: "48 shared vectors compared byte-for-byte across SDKs.", files: ["conformance/runner.ts", "conformance/vectors/envelope-v9.json"], x: 50, y: 94 },
];

export const archEdges: ArchEdge[] = [
  { from: "spec", to: "canonical", changed: true },
  { from: "spec", to: "envelope", changed: true },
  { from: "spec", to: "verify", changed: true },
  { from: "canonical", to: "envelope", changed: true },
  { from: "envelope", to: "sdk-node", changed: true },
  { from: "verify", to: "sdk-node" },
  { from: "scopes", to: "sdk-node" },
  { from: "spec", to: "sdk-rust", changed: true },
  { from: "spec", to: "sdk-py", changed: true },
  { from: "sdk-node", to: "conformance", changed: true },
  { from: "sdk-rust", to: "conformance", changed: true },
  { from: "sdk-py", to: "conformance", changed: true },
];

export const compatSDKs = ["TS core", "Node SDK", "Rust SDK", "Python SDK"];

export const compatRows: CompatRow[] = [
  {
    capability: "RFC 8785 canonicalization",
    cells: {
      "TS core": { status: "done" },
      "Node SDK": { status: "done", note: "via core" },
      "Rust SDK": { status: "done", note: "serde_jcs" },
      "Python SDK": { status: "missing", note: "json.dumps — vectors 31/34 fail" },
    },
  },
  {
    capability: "Ed25519 sign / verify",
    cells: {
      "TS core": { status: "done" },
      "Node SDK": { status: "done" },
      "Rust SDK": { status: "done", note: "dalek 2.x" },
      "Python SDK": { status: "done", note: "pynacl" },
    },
  },
  {
    capability: "Expiry + clock skew",
    cells: {
      "TS core": { status: "done", note: "30s default" },
      "Node SDK": { status: "done" },
      "Rust SDK": { status: "done", note: "30s default" },
      "Python SDK": { status: "partial", note: "time.time(), skew not configurable" },
    },
  },
  {
    capability: "Nonce replay cache",
    cells: {
      "TS core": { status: "partial", note: "in-memory only" },
      "Node SDK": { status: "done", note: "via core" },
      "Rust SDK": { status: "partial", note: "in-memory only" },
      "Python SDK": { status: "partial", note: "in-memory only" },
    },
  },
  {
    capability: "Scope matching (spec grammar)",
    cells: {
      "TS core": { status: "done", note: "trie" },
      "Node SDK": { status: "done" },
      "Rust SDK": { status: "done", note: "prefix scan" },
      "Python SDK": { status: "partial", note: "fnmatch — wider than spec" },
    },
  },
  {
    capability: "Retry with fresh nonce",
    cells: {
      "TS core": { status: "na" },
      "Node SDK": { status: "done" },
      "Rust SDK": { status: "missing", note: "no retry helper yet" },
      "Python SDK": { status: "missing", note: "no retry helper yet" },
    },
  },
];

export const timeline: TimelineEvent[] = [
  { time: "09:12", actor: "mkorkmaz", text: "opened #482 with 9 commits", kind: "system" },
  { time: "09:14", actor: "ci", text: "first run: 5/7 checks green, python + conformance failing", kind: "ci" },
  { time: "11:02", actor: "chen-w", text: "flagged per-process nonce cache", kind: "review" },
  { time: "13:40", actor: "jrmorgan", text: "traced conformance failures to json.dumps canonicalization", kind: "review" },
  { time: "14:05", actor: "mkorkmaz", text: "pushed 3 commits: scope trie in TS core, vector additions", kind: "commit" },
  { time: "15:31", actor: "aylin-t", text: "raised clock-skew spec question, fnmatch divergence", kind: "review" },
  { time: "16:10", actor: "mkorkmaz", text: "pushed 2 commits: configurable skew in TS + Rust", kind: "commit" },
  { time: "16:12", actor: "ci", text: "re-run: same 2 failures (python canonicalization)", kind: "ci" },
];

export const discussionThemes = [
  {
    id: "th-canon",
    title: "Canonicalization strategy in Python",
    stance: "Converging",
    body: "jrmorgan and aylin-t both want a real JCS implementation instead of json.dumps. Author agrees; open question is dependency (jcs package) vs port of the TS canonicalizer.",
    commentIds: ["c3"],
    insightId: "ins-canon",
  },
  {
    id: "th-skew",
    title: "Should clock skew live in the spec?",
    stance: "Agreed, pending change",
    body: "Consensus that the 30s default must be documented in §4 and configurable in every SDK. Author committed to include it in this PR.",
    commentIds: ["c1", "c2"],
    insightId: "ins-skew",
  },
  {
    id: "th-scope",
    title: "fnmatch is wider than the grammar",
    stance: "Fix requested",
    body: "aylin-t requests anchored matching in Python. No pushback. Needs conformance vectors so this class of bug is caught mechanically.",
    commentIds: ["c4"],
    insightId: "ins-scope-fnmatch",
  },
  {
    id: "th-replay",
    title: "Replay protection scope",
    stance: "Resolved: document it",
    body: "Agreement that in-memory is acceptable for v0.9 if the migration guide warns multi-instance operators. chen-w marked resolved after author committed to the doc note.",
    commentIds: ["c5"],
    insightId: "ins-nonce",
  },
];

export const suggestedNextSteps = [
  {
    id: "next-1",
    title: "Request changes: Python canonicalization",
    detail: "Block on replacing json.dumps with a JCS implementation. CI already proves the divergence; everything else in the PR is sound.",
    kind: "blocking" as const,
  },
  {
    id: "next-2",
    title: "Ask for scope-grammar conformance vectors",
    detail: "Add adversarial vectors (`?`, `[seq]`, trailing slash) so matcher drift is caught mechanically, not by review.",
    kind: "strong" as const,
  },
  {
    id: "next-3",
    title: "Approve spec change for skew",
    detail: "The §4 skew clause author committed to is uncontroversial; pre-approve to unblock.",
    kind: "normal" as const,
  },
];
