CREATE CONSTRAINT repo_id IF NOT EXISTS FOR (r:Repo) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT file_id IF NOT EXISTS FOR (f:File) REQUIRE f.id IS UNIQUE;
CREATE CONSTRAINT symbol_id IF NOT EXISTS FOR (s:Symbol) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT wiki_id IF NOT EXISTS FOR (w:WikiPage) REQUIRE w.id IS UNIQUE;
CREATE CONSTRAINT pr_id IF NOT EXISTS FOR (p:PullRequest) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT edge_id IF NOT EXISTS FOR (e:PREdge) REQUIRE e.id IS UNIQUE;
